.\adb.exe shell pm uninstall --user 0 com.lge.sizechangable.weather.platform
.\adb.exe shell pm uninstall --user 0  com.lge.appbox.client
.\adb.exe shell pm uninstall --user 0 com.lge.vrplayer
.\adb.exe shell pm uninstall --user 0 com.lge.cloudhub
.\adb.exe shell pm uninstall --user 0 com.lge.remote.lgairdrive
.\adb.exe shell pm uninstall --user 0 com.lge.LGSetupView
.\adb.exe shell pm uninstall --user 0 com.lge.ime.solution.text
.\adb.exe shell pm uninstall --user 0 com.lge.springcleaning
.\adb.exe shell pm uninstall --user 0 com.lge.lifetracker
.\adb.exe shell pm uninstall --user 0 com.lge.smartshare.provider
.\adb.exe shell pm uninstall --user 0 com.lge.myplace.engine
.\adb.exe shell pm uninstall --user 0 com.lge.launcher2.theme.optimus
.\adb.exe shell pm uninstall --user 0 com.lge.smartshare
.\adb.exe shell pm uninstall --user 0 com.lge.gallery.vr.wallpaper
.\adb.exe shell pm uninstall --user 0 com.lge.lgworld
.\adb.exe shell pm uninstall --user 0 com.lge.drive.activator
.\adb.exe shell pm uninstall --user 0 com.lge.video.vr.wallpaper
.\adb.exe shell pm uninstall --user 0 com.lge.gnsspostest
.\adb.exe shell pm uninstall --user 0 com.lge.voicecare
.\adb.exe shell pm uninstall --user 0 com.lge.nextcapture
.\adb.exe shell pm uninstall --user 0 com.lge.sync
.\adb.exe shell pm uninstall --user 0 com.lge.task
.\adb.exe shell pm uninstall --user 0 com.lge.themesquare
.\adb.exe shell pm uninstall --user 0 com.lge.sizechangable.weather.theme.optimus
.\adb.exe shell pm uninstall --user 0 com.lge.signboard.settings
.\adb.exe shell pm uninstall --user 0 com.lge.updatecenter
.\adb.exe shell pm uninstall --user 0 com.lge.smartsharepush
.\adb.exe shell pm uninstall --user 0 com.lge.qhelp.application
.\adb.exe shell pm uninstall --user 0 com.lge.myplace
.\adb.exe shell pm uninstall --user 0 com.lge.lgaccount
.\adb.exe shell pm uninstall --user 0 com.lge.videostudio
.\adb.exe shell pm uninstall --user 0 com.lge.remote.setting
.\adb.exe shell pm uninstall --user 0 com.lge.friendsmanager
.\adb.exe shell pm uninstall --user 0 com.lge.lginstallservies
.\adb.exe shell pm uninstall --user 0 com.lge.signboard
.\adb.exe shell pm uninstall --user 0 com.lge.snappage
.\adb.exe shell pm uninstall --user 0 com.facebook.katana
.\adb.exe shell pm uninstall --user 0 com.facebook.system
.\adb.exe shell pm uninstall --user 0 com.facebook.appmanager
.\adb.exe shell pm uninstall --user 0 com.evernote
.\adb.exe shell pm uninstall --user 0 com.evernote.promohelper
.\adb.exe shell pm uninstall --user 0 com.instagram.android
